name: Scheduled Trigger

on: 
    push:
        branches:
            - main
        paths:
            
    schedule: 
        - cron: '*/105 * * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm i
      run: npm i
    - name: node solarpower.js
      run: node solarpower.js
      env:
        CI: true
        BOTAPIKEY : ${{ secrets.botapikey }}
        BASE_BRANCH: main
        BRANCH: main
       